#' Find peak prominence in XRD spectrum
#'
#' @param PeakStats vector with the peak statistics.
#' @return percentage of the peak height with respect to background.
#' @examples
#' filename = xrd.getSampleFiles('asc')
#' d = xrd.import(filename)
#' q = xrd.get.PeakStats(d$TwoTheta, d$I, 38.2)
#' xrd.get.PeakProminence(q)
#' @seealso [xrd.get.PeakStats()]
#'
#' @export
xrd.get.PeakProminence <- function(PeakStats) {
  check_peak_stats(PeakStats)
  signif(PeakStats[2]/PeakStats[1]*100,3)
}

#' Checks if PeakStats was generated by xrd.get.PeakStats with correct format
#' @noRd
check_peak_stats <- function(PeakStats) {
  if (!inherits(PeakStats,"numeric")) {
    cli_warn("PeaksStats argument needs to be numerical. Generate it with xrd.get.PeakStats().")
  }
  if (!length(PeakStats)==8)  {
    cli_warn("PeakStats argument should be generated by xrd.get.PeakStats(). Make sure it has length 8.")
  }
}
